import MainNav from "src/components/navigation/MainNav";
import TopNav from "src/components/navigation/TopNav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <TopNav />
      <MainNav />
      {children}
    </div>
  );
}
