import type { Metadata } from "next";

import "./../globals.css";
import SideNav from "@/components/navigation/SideNav";
import AdminNav from "@/components/navigation/AdminNav";
import MenuBarAdmin from "@/components/navigation/MenuBarAdmin";

export const metadata: Metadata = {
  title: "Admin Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AdminNav />
      <div className="max-w-7xl mx-auto">
        <div className="h-20 my-4">
          <MenuBarAdmin />
        </div>
        <div className="flex border rounded-2xl h-screen p-4">{children}</div>
      </div>
    </>
  );
}
