import type { Metadata } from "next";

import "./../globals.css";
import SideNav from "src/components/navigation/SideNav";
import AdminNav from "src/components/navigation/AdminNav";
import MenuBarAdmin from "src/components/navigation/MenuBarAdmin";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const token = localStorage?.getItem("token");
  // if (!token) {
  //   redirect("/login");
  // }
  return (
    <>
      <AdminNav />
      <div className="max-w-7xl mx-auto">
        <div className="h-20 my-4">
          <MenuBarAdmin />
        </div>
        <div className="flex border rounded-2xl min-h-screen shadow-lg mb-6">
          {children}
        </div>
      </div>
    </>
  );
}
